/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.network_project;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;

public class RegistrationFrame extends JFrame {
    private final JTextField usernameField;
    private final JButton enterButton;

    public RegistrationFrame() {
        setTitle("Registration");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Center the window
        
        // Set a custom panel with a background image
        setContentPane(new BackgroundPanel());

        setLayout(new BorderLayout());

        // Create components
        JLabel label = new JLabel("Enter your username:", SwingConstants.CENTER);
        label.setOpaque(true); // Ensure the background color is visible
label.setBackground(new Color(233, 87, 48)); // Set the background color
label.setForeground(Color.WHITE); // Set the text color for contrast (optional)
label.setPreferredSize(new Dimension(150, 50));
label.setFont(loadCustomFont(24f)); // نفس حجم الخط مثل Waiting Room

        usernameField = new JTextField(20);
        enterButton = new JButton("Enter");

        // Transparent background for better visibility
        usernameField.setOpaque(false);
        usernameField.setBackground(new Color(0, 0, 0, 0));
        label.setFont(loadCustomFont(24f)); // Set custom font with size 24
        enterButton.setFont(loadCustomFont(18f));
        usernameField.setForeground(Color.BLACK);
        
JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER)); // Center the button
buttonPanel.add(enterButton);


enterButton.setOpaque(true);
enterButton.setBackground(Color.white); // Background color
enterButton.setForeground(new Color(255, 82, 71)); // Text color
enterButton.setFont(loadCustomFont(20f));
// Add components
        add(label, BorderLayout.NORTH);
        add(usernameField, BorderLayout.CENTER);
        add(enterButton, BorderLayout.SOUTH);
    }

    /**
     * Retrieves the entered username.
     *
     * @return the text entered in the username field.
     */
    private Font loadCustomFont(float size) {
        try {
            // Load the custom font file
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("C:\\\\Users\\\\HUAWEI\\\\Desktop\\\\Super Morning.ttf"));
            return customFont.deriveFont(size); // Return the font with the specified size
        } catch (IOException | FontFormatException e) {
            e.printStackTrace();
            return new Font("Arial", Font.PLAIN, (int) size); // Fallback font
        }
    }
    public String getUsername() {
        return usernameField.getText().trim();
    }

    /**
     * Adds an ActionListener to the Enter button.
     *
     * @param listener the ActionListener to attach.
     */
    public void addEnterButtonListener(ActionListener listener) {
        enterButton.addActionListener(listener);
    }

    // Custom JPanel to display the background image
    private static class BackgroundPanel extends JPanel {
        private final Image backgroundImage;

        public BackgroundPanel() {
            // Load the background image
            backgroundImage = new ImageIcon("C:\\Users\\HUAWEI\\Desktop\\Eye.jpg").getImage(); // Replace with your image path
        }

@Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);

    // تعيين اللون الأبيض للخلفية
    g.setColor(Color.WHITE);
    g.fillRect(0, 0, getWidth(), getHeight()); // ملء الخلفية باللون الأبيض

    // تحديد حجم الصورة ورسمها في المنتصف
    int size = Math.min(getWidth(), getHeight()); // اختيار أصغر بُعد لجعل الصورة مربعة
    int x = (getWidth() - size) / 2; // لتمركز الصورة أفقياً
    int y = (getHeight() - size) / 2; // لتمركز الصورة عمودياً
    g.drawImage(backgroundImage, x, y, size, size, this); // رسم الصورة بالحجم المربع
}

 
    }
    /**
     * Main method for testing the RegistrationFrame.
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            RegistrationFrame frame = new RegistrationFrame();
            frame.setVisible(true);

            // Example listener for testing
            frame.addEnterButtonListener(e -> {
                String username = frame.getUsername();
                if (!username.isEmpty()) {
                    JOptionPane.showMessageDialog(frame, "Welcome, " + username + "!");
                } else {
                    JOptionPane.showMessageDialog(frame, "Please enter a valid username.");
                }
            });
        });
    }
}

    // Variables declaration - do not modify                     
    // End of variables declaration
